version: "{build}"

os: Visual Studio 2015

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - c:\msys64\usr\bin\bash -lc "GOPATH=/c/gopath GOROOT=/c/Go/ /c/gopath/src/github.com/git-time-metric/gtm/script/git2go-init.sh"
  - c:\msys64\usr\bin\bash -lc "GOPATH=/c/gopath GOROOT=/c/Go/ /c/gopath/src/github.com/git-time-metric/gtm/script/appveyor-build.sh"

artifacts:
  - path: gtm.$(appveyor_repo_tag_name).windows.tar.gz
    name: gtm.zip

  - path: 'gtm.developer-build-*.windows.tar.gz'
    name: gtm-developer.tar.gz

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: O47of1Osqbk2qkk1Vn228XXF/YDwev5j5YHyNPzEPJR1pxuqwPaqlvsFDVUYQoiu
  artifact: gtm.zip
  force_update: true
  on:
    appveyor_repo_tag: true
